-- Modryn Studio — Invite-only access + admin roles
-- Migration: 004

-- user_roles: maps Neon Auth user IDs to roles
-- Populated at sign-up time. Admin email in env gets 'admin'; invite holders get 'member'.
CREATE TABLE IF NOT EXISTS user_roles (
  user_id    TEXT        PRIMARY KEY,
  role       TEXT        NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- invites: single-use invite tokens generated by the admin
-- email is optional — if set, the invite is locked to that address.
CREATE TABLE IF NOT EXISTS invites (
  token      TEXT        PRIMARY KEY,
  email      TEXT,
  created_by TEXT        NOT NULL,
  used_by    TEXT,
  used_at    TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + interval '7 days',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
